version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing Node.js dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm test # If you have tests
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying to Elastic Beanstalk...
      - eb deploy --region us-west-2
artifacts:
  files:
    - '**/*'

